// GENERATED by tools/player_sheet.py - do not edit.
//
// Regenerate with:  python tools/player_sheet.py --header
//
// Everything main.cpp needs to know about assets/COPY_player_sheet_fly.bmp, emitted
// from the one file that also validates it. V3 shipped these numbers typed
// into two places with nothing enforcing agreement - the same trap V8's
// parallax factors have - and a sheet turns four numbers into several dozen,
// so the duplication is removed rather than documented.
#pragma once
#include "physics/player.h"

namespace player_sprite {

// One animation. `wait` is in fixed simulation steps - see
// render/player_anim.h for why that is not a duration in seconds.
//
// `col` lets two animations share one row, which is Noita's model rather
// than an economy - RISE and FALL below are one row holding two poses that
// are chosen by a condition instead of advanced by a clock.
struct Anim {
    int row;
    int col;
    int frames;
    int wait;
    bool loop;
};

inline constexpr int FRAME_W = 14;
inline constexpr int FRAME_H = 26;
inline constexpr int SHEET_COLS = 6;
inline constexpr int SHEET_ROWS = 5;

// The sprite is anchored to the collision box's bottom-centre: subtract
// these from the box's top-left corner to get the frame's top-left.
inline constexpr int OFFSET_X = 3;
inline constexpr int OFFSET_Y = 6;

static_assert(FRAME_W >= Player::WIDTH && FRAME_H >= Player::HEIGHT,
              "the player sprite must be at least as large as the collision box "
              "it is anchored to; a smaller frame cannot express the offset");
static_assert(OFFSET_X == (FRAME_W - Player::WIDTH) / 2 &&
              OFFSET_Y == FRAME_H - Player::HEIGHT,
              "generated offsets disagree with Player's box - the sheet was "
              "generated against a different body size; rerun the generator");

// `inline` is load-bearing rather than stylistic, and a test caught it.
// A plain `constexpr` variable at namespace scope in a header has internal
// linkage, so every translation unit gets its *own* object at its own
// address - and render/player_anim.cpp identifies the current animation by
// pointer. Without inline, main.cpp's IDLE and player_anim.cpp's IDLE are
// different addresses, every comparison is false, and the animation restarts
// on every step: a figure that stands still twitching. It compiles, links
// and runs.
inline constexpr Anim IDLE{0, 0, 2, 30, true};
inline constexpr Anim WALK{1, 0, 6, 5, true};
inline constexpr Anim RISE{2, 0, 1, 0, true};
inline constexpr Anim FALL{2, 1, 1, 0, true};
inline constexpr Anim DIG{3, 0, 3, 8, false};
inline constexpr Anim FLY{4, 0, 6, 3, false};

// No hotspot table: the aiming arm this sheet was designed around is not
// drawn at the moment. It attached at a per-frame marker pixel carried in
// a second image the size of the sheet, which is the idea worth keeping -
// see ROADMAP.md V3.1 - but nothing is emitted for it here, because a
// table main.cpp does not read is a table nobody notices going stale.

}  // namespace player_sprite
