"""Exports PALETTE (tools/pixel_art.py) to assets/palette.gpl - the GIMP
palette format, also read directly by Aseprite and Krita. This is the "same
values exported in whatever form the external editor wants" half of V6
(ROADMAP.md): tools/pixel_art.py is the source of truth for anything built
in this repo's own scripts, this file is what a human pixel artist loads
into their editor so they are painting with the locked set from the first
stroke rather than finding out at validation time.

Regenerate after any change to PALETTE:
    python tools/export_palette_gpl.py
"""
from pixel_art import PALETTE

with open('assets/palette.gpl', 'w', newline='\n') as f:
    f.write('GIMP Palette\n')
    f.write('Name: Toop/Xoco - Forest Quantum World\n')
    f.write('Columns: 4\n')
    f.write('#\n')
    f.write('# Generated by tools/export_palette_gpl.py - do not hand-edit.\n')
    f.write('# Source of truth is PALETTE in tools/pixel_art.py; see\n')
    f.write('# notes/art_direction.txt for what each colour is for.\n')
    f.write('#\n')
    for name, (r, g, b) in PALETTE.items():
        f.write(f'{r:3d} {g:3d} {b:3d}  {name}\n')

print('wrote assets/palette.gpl')
